name: Causal Graph
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        run: |
          pip install -r requirements.txt
         
          echo " Causal Graph"
          echo "Similarity between the two dataframes" 
          cd scripts
          python Jaccard.py